module.exports = {
    s1: "start",
    s2: "menu",
    s3: "newAssist",
    s4: "users",
    s5: "category",
    s6: "newCategory",
    s7: "delCategory",
    s8: "sub",
    s9: "findNewCat",
    s10: "findDelCat",
    s11: "newSub",
    s12: "delSub",
    s13: "pro",
    s14: "findNewSub",
    s15: "findDelSub",
    s16: "findNewCatSub",
    s17: "findDelCatSub",
    s18: "kg",
    s19: "delPro",
    s20: "price",
    s21: "upload",
}