module.exports = {
    helloAdmin: "Assalomu Aleykum Glavniy Admin Hosh nma qilamiz",
    helloAssist: "Assalomu Aleykum Assist admin hosh nmani ozgartiramiz",
    helloUser: "Assalomu Aleykum siz Admin emassiz!!",
    // start
    tokenUser: "Menda Token bor🙋‍♂️",
    sendName: "Admin Ismingizni kiritgan shu Ismingizni kiriting:",
    errorToken: "Token Eskirgan",
    token: "Admin Bergan tokenni kiriting:",
    assist: "Sizni yordamchi admin sifatida bazaga qoshildi🥳. botni qayta ishga turirib yuboring♻️ /start",
    errorAssist: "Ismingiz Hatolik qildi🤔. Boshqattan ismingizi kiriting:",
    sendToken: "Bu Token ni yordamchi Adminga jonatib yuboring. Bot ga tashrif buyurib 'Menda Token bor🙋‍♂️' buyrugini kiritsinlar va tokenni botga jonatsinlar. Song siz kiritgan ismni kirgizadilar va royxatdan otadilar. \nToken👇",
    nameAssist: "Yengi Admin qoshish qoidasi: \nSiz yengi yordamchi Admin ismini kiritasiz va boshqa adminlar royxati ichida shu ismlik insonlar yagona bolishi lozim. Song biz sizga token(kalit) beramiz. Va shu yordamchi admin darxol botga kirib /start bosishi va shu tokenni kiritishi kerak boladi. Agar token tasdiqlansa biz uni yordamchi admin sifatida uni ham bazi buyruqlariga javob beramiz. Agar yordamchi admin qoshish fikringizdan qaytga bolsangiz: /ortga buyrugini yozib yuboring \n\nYengi Yordamchi Admin ismini kiriting....",
    errorName: "Kechirasiz siz kiritgan yordamchi admin ismi avval bor edi.😢",
    // New Assist
    newAssist: "Yengi Assist qoshish",
    category: "Category Nazorati",
    users: "Userlarni korish",
    subCategory: "subCategory Nazorati",
    product: "Product Nazorati",
    // Keyboard
    startCategory: "Category Nazorati \nHozirda active categorylar soni: ",
    keyboradNewCategory: "Yengi Category qoshish✍️",
    keyboradDelCategory: "Mavjud Category Ochirish❌",
    newCategory: "Yengi Category nomini kiriting:",
    delCategory: "Ochiriladigan Category nomini tanlang:",
    // New Category
    startSubCategory: "SubCategoy Nazorati \nHozirda active subCategorylar soni: ",
    findNewCategory: "Qaysi Category ga qoshamiz ✍️",
    findDelCategory: "Qaysi Category dan ochiramiz ❌",
    keyboradNewsubCategory: "Yengi subCategory qoshish✍️",
    keyboradDelsubCategory: "Mavjud subCategory Ochirish❌",
    newSub: "Yengi subCategory nomini kiriting:",
    delSub: "Ochiriladigan subCategory nomini tanlang:",
    nullSub: "Bu Categoryga tegishli SubCategory yoq",
    errSub: "Iltimos yengi SubCategory nomini boyagi sms ga reply qilib kiriting",
    upload: "Shu Mahsulotni rasmini kiriting:",
    errUpload: "Mahsulot rasmini shunchaki Photo qilib yuklang",
    // New SubCategory
    startProduct: "Product Nazorati \nHozirda active Productlar soni: ",
    findNewSubPro: "Qaysi SubCategory ga qoshamiz",
    newPro: "Yengi Product nomini kiriting: ",
    errPro: "Iltimos yengi Product malumotlarini boyagi sms ga reply qilib kiriting",
    errorPro: "Narxni togri kiriting masalan: Masalan(100 000)",
    saveProOlchov: "ning olchovini kiriting: Masalan(1kg)",
    saveProPrice: "ning narxini kiriting: Masalan(100 000)",
    delPro: "ga tegishli qaysi birini ochiramiz:",
    nullPro: "Bu SubCategory ga tegishli Productlar topilmadi",
    // Product
    main: "Main Menu",
    back: "Come Back",
    save: "Malumotlar Bazasiga qoshildi✅",
    del: "Malumotlar Bazasidan Ochirildi🗑"
}